### ISSUE TITLE
[Bug] No space for escaped bounty

### ISSUE THREAD

**Issue by Trimatix** [GOF2BountyBot/GOF2BountyBot#429]
**Describe the bug**
Lost a duel to a criminal, but when they tried to escape, the division had no space for them. Potential race condition?

**Steps to reproduce**
Unknown

**Message link**
https://discord.com/channels/711548456019296289/721311036891725856/880834540795482192

**Error Trace**
```py
(27/082021-15:21)-[MAIN::ON_MESSAGE]>OverflowError: An unexpected error occured when calling command 'check' with args 'pescal inartu'
Traceback (most recent call last):
  File "/root/New-BountyBot/bot/bot.py", line 588, in on_message
    commandFound = await botCommands.call(command, message, args, accessLevel, isDM=isDM)
  File "/root/New-BountyBot/bot/commandsManager/heirarchicalCommandsDB.py", line 166, in call
    await self.commands[requiredAccess][command].call(message, args, isDM)
  File "/root/New-BountyBot/bot/commandsManager/commandRegistry.py", line 71, in call
    await self.func(message, args if self.forceKeepArgsCasing else args.lower(), isDM)
  File "/root/New-BountyBot/bot/commands/usr_bounties.py", line 246, in cmd_check
    bounty.escape()
  File "/root/New-BountyBot/bot/gameObjects/bounties/bounty.py", line 259, in escape
    self.division.owningDB.addEscapedBounty(self, dbReload=dbReload)
  File "/root/New-BountyBot/bot/databases/bountyDB.py", line 371, in addEscapedBounty
    raise OverflowError(f"Division for the escaped bounty ({bounty.criminal.name}, level {bounty.techLevel}) is full")
OverflowError: Division for the escaped bounty (Oluchi Erland, level 5) is full
```

**Comment by Trimatix** [comment]
should be fixed by https://github.com/GOF2BountyBot/GOF2BountyBot/pull/583
