### ISSUE TITLE
[Bug] `/pay` fails

### ISSUE THREAD

**Issue by Trimatix** [GOF2BountyBot/GOF2BountyBot#890]
**Describe the bug**
bot responds, but neither balance is updated

**Steps to reproduce**
1. `/pay` someone any amount

**Exception trace**
```py
(10/01/22:13)-[BOT.COGS.USERECONOMYCOG::CMD_PAY]>CommandInvokeError: Command 'pay' raised an exception: TypeError: '_MissingSentinel' object is not iterable
Traceback (most recent call last):
  File "/root/bb10testingenv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 861, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/New-BountyBot/bot/cogs/UserEconomyCog.py", line 389, in cmd_pay
    await targetBUser.individualNotify(self.bot, f":moneybag: {interaction.user.mention} paid you **{amount}** credits!")
  File "/root/New-BountyBot/bot/users/basedUser.py", line 1074, in individualNotify
    message = await sender.send(content=content, tts=tts,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bb10testingenv/lib/python3.11/site-packages/discord/abc.py", line 1500, in send
    sticker_ids: SnowflakeList = [sticker.id for sticker in stickers]
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '_MissingSentinel' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/bb10testingenv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/root/bb10testingenv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bb10testingenv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'pay' raised an exception: TypeError: '_MissingSentinel' object is not iterable
```

**Comment by Trimatix** [comment]
make it ping the target user while your there
