### ISSUE TITLE
[Bug] `/sell` ship fails

### ISSUE THREAD

**Issue by Trimatix** [GOF2BountyBot/GOF2BountyBot#895]
**Describe the bug**
Bot doesn't respond

**Steps to reproduce**
Steps to reproduce the bug. E.g:
1. Have a ship in your hangar
2. `/sell` it
3. Observe error

*(optional)* **Your discord tag**
Bluefire

**Comment by Trimatix** [comment]
This is the exception trace:
```py
(14/01/18:17)-[interaction#1063884693407285389][BOT.COGS.USERECONOMYCOG::CMD_SHOP_SELL]>CommandInvokeError: Command 'sell' raised an exception: NotImplementedError: Unsupported item type: Ship
Traceback (most recent call last):                              File "/root/bb10testingenv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 861, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                          File "/root/New-BountyBot/bot/cogs/UserEconomyCog.py", line 339, in cmd_shop_sell                                             shop.userSellItem(bUser, requestedItem)                     File "/root/New-BountyBot/bot/gameObjects/guildShop.py", line 517, in userSellItem                                            raise NotImplementedError(f"Unsupported item type: {type(item).__name__}")                                              NotImplementedError: Unsupported item type: Ship
```
